version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    versioning-strategy: "increase"
    assignees:
      - ShadowZ11
    groups:
      npm-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    reviewers:
      - Asma-B-M
      - ShadowZ11
    assignees:
      - ShadowZ11
    target-branch: "main"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5