#packages:
#  - '.'
#  - 'examples/*'

allowBuilds:
  '@nestjs/core': true
  '@swc/core': true
  esbuild: true
  puppeteer: true
  unrs-resolver: false

minimumReleaseAge: 4320 # 3 days

trustPolicy: no-downgrade

trustPolicyIgnoreAfter: 20160 # 14 days
